TickerOCHL:
   name: "TickerOCHLAll"
   fields:
     -
       name: 'country'
       dtype: 'char(32)'
     -
       name: 'ticker'
       dtype: 'char(4)'
     -
       name: 'date'
       dtype: 'datetime'
     -
       name: 'open'
       dtype: 'decimal(6,3)'
     -
       name: 'high'
       dtype: 'decimal(6,3)'
     -
       name: 'low'
       dtype: 'decimal(6,3)'
     -
       name: 'close'
       dtype: 'decimal(6,3)'
     -
       name: 'volume'
       dtype: 'decimal(6,3)'
     -
       name: 'dividends'
       dtype: 'decimal(6,3)'
     -
       name: 'stocksplits'
       dtype: 'decimal(6,3)'
