TickerList:
   name: "TickerList"
   fields:
     -
       name: 'country'
       dtype: 'char(32)'
     -
       name: 'ticker'
       dtype: 'char(4)'
     -
       name: 'securityname'
       dtype: 'char(32)'
     -
       name: 'exchange'
       dtype: 'char(32)'
     -
       name: 'sector_gf'
       dtype: 'char(32)'
